version: '2'
services:
  web:  
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
#    entrypoint:
#      ["python", "manage.py","run"]
    env_file:
      - flask_variables.env
#    environment:
#      APP_ENV: "development"
#      APP_DEBUG: "True"
#      APP_PORT: 5000 
#      MONGODB_USERNAME: user1 
#      MONGODB_PASSWORD: rokwiredatabase
#      MONGODB_HOSTNAME: cluster0-fnqs2.mongodb.net/test?retryWrites=true&w=majority
#      MONGODB_DATABASE: foodtrucktracker  
